config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'
  get 'about', to: 'about#show'
  get 'signup', to: 'users#new'
  post 'users',  to: 'users#create'
  get 'login', to: 'session#new'
  post 'login', to: 'session#create'
  get 'logout', to: 'session#destroy'
  resources :products, only: [:index, :show]
  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, except: [:edit, :update, :show, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :products

end

app/models/line_item.rb
class LineItem < ApplicationRecord

  belongs_to :order
  belongs_to :product

  monetize :item_price_cents, numericality: true
  monetize :total_price_cents, numericality: true

end

app/models/order.rb
class Order < ApplicationRecord
  
  has_many :line_items

  monetize :total_cents, numericality: true

  validates :stripe_charge_id, presence: true

end

app/models/product.rb
class Product < ApplicationRecord
  monetize :price_cents, numericality: true
  mount_uploader :image, ProductImageUploader

  belongs_to :category

  validates :name, presence: true
  validates :price, presence: true
  validates :quantity, presence: true
  validates :category, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true

 
  def self.authenticate_with_credentials(email, password)
    user = find_by_email(email.strip.downcase)
    user && user.authenticate(password)
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  def show
    @products = Product.all
    @categories = Category.all
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  http_basic_authenticate_with name: ENV["ADMIN_USERNAME"], password: ENV["ADMIN_PASSWORD"]
  def index
    @products = Product.order(id: :desc).all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to [:admin, :products], notice: 'Product created!'
    else
      render :new
    end
  end

  def destroy
    @product = Product.find params[:id]
    @product.destroy
    redirect_to [:admin, :products], notice: 'Product deleted!'
  end

  private

  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :category_id,
      :quantity,
      :image,
      :price
    )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

  private

  def cart
    @cart ||= cookies[:cart].present? ? JSON.parse(cookies[:cart]) : {}
  end
  helper_method :cart

  def enhanced_cart
    @enhanced_cart ||= Product.where(id: cart.keys).map {|product| { product:product, quantity: cart[product.id.to_s] } }
  end
  helper_method :enhanced_cart

  def cart_subtotal_cents
    enhanced_cart.map {|entry| entry[:product].price_cents * entry[:quantity]}.sum
  end
  helper_method :cart_subtotal_cents


  def update_cart(new_cart)
    cookies[:cart] = {
      value: JSON.generate(new_cart),
      expires: 10.days.from_now
    }
    cookies[:cart]
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    if cart.empty?
       render 'empty'
    else
      render 'show'
    end

  end

  def add_item
    product_id = params[:product_id].to_s
    modify_cart_delta(product_id, +1)

    redirect_back fallback_location: root_path
  end

  def remove_item
    product_id = params[:product_id].to_s
    modify_cart_delta(product_id, -1)

    redirect_back fallback_location: root_path
  end

  private

  def modify_cart_delta(product_id, delta)
    cart[product_id] = (cart[product_id] || 0) + delta
    cart.delete(product_id) if cart[product_id] < 1
    update_cart cart
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:id])
    @products = @category.products.order(created_at: :desc)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
  end

  def create
    charge = perform_stripe_charge
    order = create_order(charge)

    if order.valid?
      empty_cart!
      redirect_to order, notice: 'Your Order has been placed.'
    else
      redirect_to cart_path, flash: { error: order.errors.full_messages.first }
    end
  rescue Stripe::CardError => e
    redirect_to cart_path, flash: { error: e.message }
  end

  private

  def empty_cart!
    # empty hash means no products in cart :)
    update_cart({})
  end

  def perform_stripe_charge
    Stripe::Charge.create(
      source: params[:stripeToken],
      amount: cart_subtotal_cents,
      description: "Khurram Virani's Jungle Order",
      currency: 'cad'
    )
  end

  def create_order(stripe_charge)
    order = Order.new(
      email: params[:stripeEmail],
      total_cents: cart_subtotal_cents,
      stripe_charge_id: stripe_charge.id
    )

    enhanced_cart.each do |entry|
      product = entry[:product]
      quantity = entry[:quantity]
      order.line_items.new(
        product: product,
        quantity: quantity,
        item_price: product.price,
        total_price: product.price * quantity
      )
    end

    if order.save
      # Send email receipt using OrderMailer
      OrderMailer.order_email(order).deliver_later

      order
    else
      respond_to do |format|
        format.html { render action: 'new' }
      end
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all.order(created_at: :desc)
  end

  def show
    @product = Product.find params[:id]
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.authenticate_with_credentials(params[:email], params[:password])

    if user
      session[:user_id] = user.id
      redirect_to '/'
    else
      # If user's login doesn't work, send them back to the login form.
      redirect_to '/login', alert: 'Invalid email or password'
    end
  end


  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  private
def user_params
  params.require(:user).permit(
    :name, :email, :password, :password_confirmation)
end

end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/about/show.html.erb
<section class="about-us">
  <h1>About Us</h1>
  <p>Our mission is to provide the best products at the best prices. Find all the amazing products at affordable prices. If you found a cheaper price elsewhere, we can match the price✔👌</p>

  <div class="team-container">
    <h2>Our Team</h2>
    <div class="team">    
    <div class="member">
    <img src="https://ca.slack-edge.com/T02MD9XTF-U02M4JZ8Z-0b5e8f6d7b4d-512" alt="member">
    <h3>Yunus Emre Aybey</h3>
    <p>Backend Developer</p>
  </div>
  <div class="member">
    <img src="https://ca.slack-edge.com/T02MD9XTF-U02M4JZ8Z-0b5e8f6d7b4d-512" alt="member">
    <h3>Akoms Eroms</h3>
    <p>Frontend Developer</p>
  </div>
  <div class="member">
    <img src="https://ca.slack-edge.com/T02MD9XTF-U02M4JZ8Z-0b5e8f6d7b4d-512" alt="member">
    <h3>Saratu Ismaila</h3>
    <p>Lead Developer</p>
  </div>
  </div>
  </div>
   <div class="header-container">
   <h2>Our Story</h2>
   <p>Our story begins with a simple idea: to make shopping easier and more fun. We've always believed in the power and potential of technology to improve people's lives. And over the years, we've worked hard to build an experience that does just that. We're here to help you find your perfect product.</p>
 
   <h2>Our Values</h2>
   <p>Our values are the foundation of our company. They guide our actions and behavior. They influence the way we work with each other – and the way we serve our clients and engage with our communities. We believe in acting with integrity. We believe in treating each other with respect and dignity. We believe in our people.</p>
 
   <h2>Our Culture</h2>
   <p>Our culture is the foundation of our company. It’s what makes us unique. It’s what makes us different. It’s what makes us special. It’s what makes us who we are.</p>
   </div>
  

  <%= link_to "Continue Shopping", root_path, class: 'btn btn-lg btn-primary' %>
</section>

app/views/admin/dashboard/show.html.erb
<section class="dashboard-details">
  <h2>Store Stats</h2>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Total No of Products</th>
        <th>Number of Categories</th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td><%= @products.count %></td>
          <td><%= @categories.count %></td>
        </tr>
    </tbody>
  </table>
  <%= link_to "See all Products", "/admin/products",  class: 'btn btn-lg btn-primary' %>
</section>

app/views/carts/_item.html.erb
<tr>
  <td>
    <%= image_tag product.image.tiny.url %>
  </td>
  <td>
    <h4><%= product.name %></h4>
    <br>
    <p><%= product.description %></p>
  </td>
  <td>
  <span class="cart-subtotal_money">$<%= product.price %></span>
  </td>
  <td>
    <div>
    <%= button_to remove_item_cart_path(product_id: product.id), class: 'btn btn-xs btn-danger' do %> - <% end %>
    <%= quantity %>
    <%= button_to add_item_cart_path(product_id: product.id), class: 'btn btn-xs btn-success' do %> + <% end %>
    </div>
  </td>
  <td>
  <span class="cart-subtotal_money">$<%= product.price * quantity %></span>
  </td>
</tr>

app/views/carts/empty.html.erb
<header class="page-header">
    <h1>My Cart</h1>
  </header>
  <h1>Your cart is empty</h1>
  <a href="/products">Continue Shopping</a>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

app/views/carts/show.html.erb
<section class="cart-show">

  <header class="page-header">
    <h1>My Cart</h1>
  </header>
  <div class="panel panel-default items">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2">Product</th>
          <th>Unit Price</th>
          <th>Quantity</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        <% enhanced_cart.each do |item| %>
          <%= render 'item', product: item[:product], quantity: item[:quantity].to_i %>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <th colspan="4">
            TOTAL:
          </th>
          <th>
          <span class="cart-subtotal_money">$<%= cart_subtotal_cents / 100.0 %></span>
          </th>
        </tr>
      </tfoot>
    </table>
  </div>

  <div class="row">
    <div class="col-xs-12">
      <%= form_tag orders_path do %>
        <script
          src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-amount="<%= cart_subtotal_cents %>"
          data-name="Jungle"
          data-description="Khurram Virani's Jungle Order"
          data-locale="auto"
          data-email="kvirani@gmail.com"
          data-currency="cad">
        </script>
      <% end %>
    </div>
  </div>

</section>